### ISSUE TITLE
Set up Login and Auth

### ISSUE THREAD

**Issue by pedro-camargo11** [Team-53-CEN3031/CEN3031_DEPP_53#1]
Acceptance Criteria:

● The user is able to log in using either a unique email, along with a password.
● Username and passwords are going to be stored in an encrypted database, and never
stored in plain text.
● User emails will not be given to third parties for any purpose.
● Users who forget their login details will be prompted to recover their email using a
related phone number, and users who forget their passwords will be allowed to reset their
passwords through their emails.

**Comment by zachtyson** [comment]
Finished first bullet, Christian is currently working on second bullet. Haven't even started fourth bullet yet
